### ISSUE TITLE
How could one use fractions as keys ?

### ISSUE THREAD

**Issue by Stepland** [NicoG60/interval-tree#1]
Hi !

First of all, thanks a ton for the incredible work, this lib looks awesome.

I'm trying to use it to store intervals of _fractions_ (currently trying the ones from boost), and it's triggering an error because of this bit (I believe) :
```cpp
typename std::enable_if<std::is_arithmetic<Key>::value, int>::type = 0
```

Is there a way for me, on the client-side, to make `interval_tree` accept more exotic number types without touching the lib's code ?

If not, would there need to be _major_ code changes to relax that requirement on `Key` ? If that's the only solution, I'm willing to try making a PR, but I would like your help to get a general idea of what would need to be changed.

Thanks

**Comment by NicoG60** [comment]
Hi Stepland

Thanks for your time writing this, appreciate the kind word! I think it shouldn't be that far stretch to accept fraction type as long as the type is clearly orderable.
The restriction for arithmetic type was just a way to simplify the problem and was closer to my use case: ordering and looking through events in time.

A good way to do that would be to do as the STL does, having a Comparator object in the template which defaults to `std::less`

Feel free to have a look at the code base and make a PR if you're motivated doing so!

Otherwise, let's just keep in touch and I'll have a look at that shortly

Thanks

**Comment by Stepland** [comment]
I'll give making a PR a go, thanks for the fast answer !

**Comment by Stepland** [comment]
It looks like this was already partially implemented so thankfully this did not take long
